ALTER TABLE `ai_feedback` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `badge_progress` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `brand_assets` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `brand_profile` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `call_grades` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `calls` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `campaign_kpis` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `content_ideas` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `deals` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `grading_rules` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `kpi_channels` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `kpi_deals` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `kpi_goals` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `kpi_markets` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `kpi_periods` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `lead_gen_staff` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `performance_metrics` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `reward_views` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `social_posts` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `team_assignments` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `team_member_kpis` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `team_members` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `team_training_items` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `training_materials` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user_badges` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user_streaks` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user_xp` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `tenantId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `xp_transactions` MODIFY COLUMN `tenantId` int NOT NULL;