'use client'
// components/inventory/PropertyFlyer.tsx
// PDF flyer generation for deal blasts — includes specs + description
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#FFFFFF' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#C0392B', paddingBottom: 12 },
  brand: { fontSize: 24, fontWeight: 'bold', color: '#C0392B' },
  badge: { fontSize: 10, color: '#666666', textTransform: 'uppercase', letterSpacing: 2 },
  address: { fontSize: 22, fontWeight: 'bold', color: '#1A1A18', marginBottom: 4 },
  cityState: { fontSize: 14, color: '#6B6B66', marginBottom: 6 },
  specsRow: { flexDirection: 'row', marginBottom: 16 },
  specItem: { fontSize: 11, color: '#4A4A46', marginRight: 16 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 16 },
  gridItem: { width: '50%', paddingVertical: 8, paddingHorizontal: 4 },
  gridLabel: { fontSize: 9, color: '#9B9A94', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 2 },
  gridValue: { fontSize: 18, fontWeight: 'bold', color: '#1A1A18' },
  greenValue: { fontSize: 18, fontWeight: 'bold', color: '#1D9E75' },
  amberValue: { fontSize: 18, fontWeight: 'bold', color: '#BA7517' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 'bold', color: '#C0392B', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#F0EEE9', paddingBottom: 4 },
  description: { fontSize: 10, color: '#6B6B66', lineHeight: 1.6, marginBottom: 16 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTopWidth: 1, borderTopColor: '#F0EEE9', paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#9B9A94' },
})

function fmt(v: string | null): string {
  if (!v) return '—'
  return `$${Number(v).toLocaleString()}`
}

export interface FlyerProps {
  address: string; city: string; state: string; zip: string
  askingPrice: string | null; arv: string | null; contractPrice: string | null
  assignmentFee: string | null; mao: string | null
  beds?: number | null; baths?: number | null; sqft?: number | null; yearBuilt?: number | null
  description?: string | null
}

function PropertyFlyerDoc(props: FlyerProps) {
  const { address, city, state, zip, askingPrice, arv, contractPrice, assignmentFee, mao, beds, baths, sqft, yearBuilt, description } = props
  const hasSpecs = beds || baths || sqft || yearBuilt

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Gunner</Text>
          <Text style={styles.badge}>Investment Opportunity</Text>
        </View>

        <Text style={styles.address}>{address}</Text>
        <Text style={styles.cityState}>{city}, {state} {zip}</Text>

        {hasSpecs && (
          <View style={styles.specsRow}>
            {beds ? <Text style={styles.specItem}>{beds} Bed</Text> : null}
            {baths ? <Text style={styles.specItem}>{baths} Bath</Text> : null}
            {sqft ? <Text style={styles.specItem}>{sqft.toLocaleString()} Sqft</Text> : null}
            {yearBuilt ? <Text style={styles.specItem}>Built {yearBuilt}</Text> : null}
          </View>
        )}

        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Asking Price</Text>
            <Text style={styles.gridValue}>{fmt(askingPrice)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>ARV</Text>
            <Text style={styles.greenValue}>{fmt(arv)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Contract Price</Text>
            <Text style={styles.gridValue}>{fmt(contractPrice)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Assignment Fee</Text>
            <Text style={styles.amberValue}>{fmt(assignmentFee)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>MAO</Text>
            <Text style={styles.gridValue}>{fmt(mao)}</Text>
          </View>
        </View>

        {description && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Property Details</Text>
            <Text style={styles.description}>{description}</Text>
          </View>
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by Gunner AI</Text>
          <Text style={styles.footerText}>{new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  )
}

export async function generatePropertyPDF(props: FlyerProps): Promise<Blob> {
  const blob = await pdf(<PropertyFlyerDoc {...props} />).toBlob()
  return blob
}

export function downloadPropertyPDF(props: FlyerProps) {
  generatePropertyPDF(props).then(blob => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${props.address.replace(/[^a-zA-Z0-9]/g, '_')}_flyer.pdf`
    a.click()
    URL.revokeObjectURL(url)
  })
}
