'use client'
// components/inventory/PropertyFlyer.tsx
// PDF flyer generation for deal blasts
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#FFFFFF' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#C0392B', paddingBottom: 12 },
  brand: { fontSize: 24, fontWeight: 'bold', color: '#C0392B' },
  badge: { fontSize: 10, color: '#666666', textTransform: 'uppercase', letterSpacing: 2 },
  address: { fontSize: 22, fontWeight: 'bold', color: '#1A1A18', marginBottom: 4 },
  cityState: { fontSize: 14, color: '#6B6B66', marginBottom: 20 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 20 },
  gridItem: { width: '50%', paddingVertical: 8, paddingHorizontal: 4 },
  gridLabel: { fontSize: 9, color: '#9B9A94', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 2 },
  gridValue: { fontSize: 18, fontWeight: 'bold', color: '#1A1A18' },
  greenValue: { fontSize: 18, fontWeight: 'bold', color: '#1D9E75' },
  amberValue: { fontSize: 18, fontWeight: 'bold', color: '#BA7517' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 'bold', color: '#C0392B', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#F0EEE9', paddingBottom: 4 },
  detailRow: { flexDirection: 'row', marginBottom: 4 },
  detailLabel: { fontSize: 10, color: '#9B9A94', width: 100 },
  detailValue: { fontSize: 10, color: '#1A1A18' },
  description: { fontSize: 10, color: '#6B6B66', lineHeight: 1.5 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTopWidth: 1, borderTopColor: '#F0EEE9', paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#9B9A94' },
})

function fmt(v: string | null): string {
  if (!v) return '—'
  return `$${Number(v).toLocaleString()}`
}

interface FlyerProps {
  address: string; city: string; state: string; zip: string
  askingPrice: string | null; arv: string | null; contractPrice: string | null
  assignmentFee: string | null; mao: string | null
}

function PropertyFlyerDoc({ address, city, state, zip, askingPrice, arv, contractPrice, assignmentFee, mao }: FlyerProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Gunner</Text>
          <Text style={styles.badge}>Investment Opportunity</Text>
        </View>

        <Text style={styles.address}>{address}</Text>
        <Text style={styles.cityState}>{city}, {state} {zip}</Text>

        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Asking Price</Text>
            <Text style={styles.gridValue}>{fmt(askingPrice)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>ARV</Text>
            <Text style={styles.greenValue}>{fmt(arv)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Contract Price</Text>
            <Text style={styles.gridValue}>{fmt(contractPrice)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>Assignment Fee</Text>
            <Text style={styles.amberValue}>{fmt(assignmentFee)}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.gridLabel}>MAO</Text>
            <Text style={styles.gridValue}>{fmt(mao)}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by Gunner AI</Text>
          <Text style={styles.footerText}>{new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  )
}

export async function generatePropertyPDF(props: FlyerProps): Promise<Blob> {
  const blob = await pdf(<PropertyFlyerDoc {...props} />).toBlob()
  return blob
}

export function downloadPropertyPDF(props: FlyerProps) {
  generatePropertyPDF(props).then(blob => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${props.address.replace(/[^a-zA-Z0-9]/g, '_')}_flyer.pdf`
    a.click()
    URL.revokeObjectURL(url)
  })
}
