import type { IndustryPlaybook, RoleDef, StageDef, CallTypeDef, RubricDef, AlgorithmConfig, RoleplayPersona, TrainingCategory, GradingPhilosophy } from "../../shared/types";

const ROLES: RoleDef[] = [
  { code: "acquisitions", name: "Acquisitions Manager", description: "Negotiates deals with sellers, runs comps, makes offers", color: "#6366f1" },
  { code: "dispositions", name: "Dispositions Manager", description: "Sells contracts to cash buyers, manages buyer list", color: "#8b5cf6" },
  { code: "lead_manager", name: "Lead Manager", description: "First contact with inbound leads, qualifies and routes", color: "#0ea5e9" },
  { code: "tc", name: "Transaction Coordinator", description: "Manages contracts, title, inspections through closing", color: "#10b981" },
];

const STAGES: StageDef[] = [
  { code: "new_lead", name: "New Lead", pipeline: "acquisitions", order: 0 },
  { code: "contacted", name: "Contacted", pipeline: "acquisitions", order: 1 },
  { code: "qualified", name: "Qualified", pipeline: "acquisitions", order: 2 },
  { code: "appointment_set", name: "Appointment Set", pipeline: "acquisitions", order: 3 },
  { code: "offer_made", name: "Offer Made", pipeline: "acquisitions", order: 4 },
  { code: "under_contract", name: "Under Contract", pipeline: "acquisitions", order: 5 },
  { code: "dispo", name: "In Dispo", pipeline: "dispositions", order: 6 },
  { code: "assigned_buyer", name: "Assigned to Buyer", pipeline: "dispositions", order: 7 },
  { code: "closing", name: "Closing", pipeline: "dispositions", order: 8 },
  { code: "closed", name: "Closed", pipeline: "dispositions", order: 9 },
  { code: "dead", name: "Dead", pipeline: "acquisitions", order: 99 },
];

const CALL_TYPES: CallTypeDef[] = [
  {
    code: "cold_call",
    name: "Cold Call",
    description: "First outreach to a new lead from a list",
    coachingChips: ["How do I handle 'I'm not interested'?", "Tips for building rapport fast", "How to get a seller to open up?"],
    actionChips: ["Add note to contact", "Create task: Follow up next week", "Send SMS: Still interested in an offer?"],
  },
  {
    code: "warm_call",
    name: "Warm Call",
    description: "Follow-up with a lead who has shown interest",
    coachingChips: ["How do I qualify motivation quickly?", "What questions reveal true timeline?", "Tips for uncovering hidden objections"],
    actionChips: ["Add note with qualification summary", "Change pipeline stage", "Create task: Schedule walkthrough"],
  },
  {
    code: "inbound",
    name: "Inbound Call",
    description: "Seller-initiated call from marketing",
    coachingChips: ["How do I qualify motivation quickly?", "What questions reveal true timeline?", "Tips for uncovering hidden objections"],
    actionChips: ["Add note with qualification summary", "Change pipeline stage", "Create task: Schedule walkthrough"],
  },
  {
    code: "follow_up",
    name: "Follow Up",
    description: "Scheduled callback or nurture touch",
    coachingChips: ["How do I re-engage a cold lead?", "Tips for following up without being pushy", "What to say when they stopped responding"],
    actionChips: ["Add note to contact", "Send SMS: Following up on our conversation", "Create task: Call back next week"],
  },
  {
    code: "offer_call",
    name: "Offer Call",
    description: "Presenting or negotiating an offer with the seller",
    coachingChips: ["How do I handle 'price too low'?", "Tips for anchoring value", "How to create urgency without pressure?"],
    actionChips: ["Add note with offer details", "Change pipeline stage", "Schedule follow-up call"],
  },
  {
    code: "dispo_call",
    name: "Dispo Call",
    description: "Pitching a deal to a cash buyer",
    coachingChips: ["How do I pitch a deal to a buyer?", "Tips for handling buyer objections on price", "How to create urgency with buyers?"],
    actionChips: ["Add note: Dispo call summary", "Send SMS to buyer", "Create appointment: Property walkthrough"],
  },
];

const RUBRICS: RubricDef[] = [
  {
    id: "acq-cold",
    name: "Acquisitions Cold Call",
    role: "acquisitions",
    callType: "cold_call",
    totalPoints: 100,
    criticalFailures: [
      "Caller does not confirm seller's name",
      "Caller makes an offer without asking about motivation",
      "Caller is rude or argumentative",
    ],
    talkRatioTarget: { min: 30, max: 45 },
    criteria: [
      { name: "Introduction & Rapport", maxPoints: 15, description: "Introduces self and company clearly, builds initial rapport" },
      { name: "Reason for Call", maxPoints: 10, description: "States purpose clearly — why calling about their property" },
      { name: "Seller Motivation", maxPoints: 20, description: "Uncovers why the seller wants/needs to sell (timeline, situation)" },
      { name: "Property Condition", maxPoints: 15, description: "Asks about condition, repairs needed, occupancy" },
      { name: "Financial Discovery", maxPoints: 15, description: "Discovers mortgage balance, liens, asking price expectations" },
      { name: "Timeline & Urgency", maxPoints: 10, description: "Establishes seller's timeline and urgency level" },
      { name: "Next Steps & Close", maxPoints: 15, description: "Sets a clear next step — appointment, follow-up, or offer" },
    ],
  },
  {
    id: "acq-warm",
    name: "Acquisitions Warm/Follow-Up",
    role: "acquisitions",
    callType: "warm_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not reference previous conversation or context",
      "Pushes for appointment without re-qualifying",
    ],
    talkRatioTarget: { min: 30, max: 50 },
    criteria: [
      { name: "Context Recall", maxPoints: 15, description: "References previous conversation, builds continuity" },
      { name: "Updated Situation", maxPoints: 20, description: "Checks if anything has changed since last contact" },
      { name: "Deeper Motivation", maxPoints: 20, description: "Digs deeper into seller's pain points and motivation" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles seller objections professionally and persuasively" },
      { name: "Commitment / Next Step", maxPoints: 15, description: "Secures appointment, offer acceptance, or concrete next step" },
      { name: "Tone & Empathy", maxPoints: 10, description: "Maintains professional, empathetic tone throughout" },
    ],
  },
  {
    id: "acq-offer",
    name: "Acquisitions Offer Presentation",
    role: "acquisitions",
    callType: "offer_call",
    totalPoints: 100,
    criticalFailures: [
      "Presents number without justification or context",
      "Gets defensive when seller pushes back on price",
    ],
    talkRatioTarget: { min: 35, max: 50 },
    criteria: [
      { name: "Recap & Frame", maxPoints: 15, description: "Recaps seller situation before presenting number" },
      { name: "Number Presentation", maxPoints: 20, description: "Presents offer confidently with clear justification" },
      { name: "Value Anchoring", maxPoints: 15, description: "Anchors value on convenience, speed, certainty — not just price" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles price pushback calmly and with logic" },
      { name: "Urgency Creation", maxPoints: 15, description: "Creates appropriate urgency without pressure tactics" },
      { name: "Contract / Close", maxPoints: 15, description: "Moves toward contract signing or clear counter path" },
    ],
  },
  {
    id: "acq-inbound",
    name: "Inbound Seller Call",
    role: "lead_manager",
    callType: "inbound",
    totalPoints: 100,
    criticalFailures: [
      "Does not capture seller's name and property address",
      "Lets caller hang up without setting a next step",
    ],
    talkRatioTarget: { min: 25, max: 40 },
    criteria: [
      { name: "Speed & Energy", maxPoints: 15, description: "Answers promptly with enthusiasm and professionalism" },
      { name: "Information Capture", maxPoints: 20, description: "Captures name, address, phone, email within first 2 min" },
      { name: "Qualification", maxPoints: 20, description: "Asks motivation, timeline, condition, price expectations" },
      { name: "Rapport Building", maxPoints: 15, description: "Builds trust and makes seller feel comfortable" },
      { name: "Appointment Setting", maxPoints: 20, description: "Converts call to a scheduled appointment or callback" },
      { name: "CRM Entry", maxPoints: 10, description: "Confirms info will be captured and follow-up scheduled" },
    ],
  },
  {
    id: "dispo-buyer",
    name: "Dispositions Buyer Call",
    role: "dispositions",
    callType: "dispo_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not confirm buyer's buying criteria before pitching",
      "Cannot answer basic questions about the property",
    ],
    talkRatioTarget: { min: 40, max: 55 },
    criteria: [
      { name: "Buyer Criteria Confirm", maxPoints: 15, description: "Confirms buyer's target area, price range, and property type" },
      { name: "Deal Presentation", maxPoints: 25, description: "Presents deal clearly — address, ARV, rehab estimate, assignment fee" },
      { name: "Urgency & Scarcity", maxPoints: 15, description: "Communicates deal timeline and competitive interest" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles buyer concerns about numbers, area, condition" },
      { name: "Closing for Commitment", maxPoints: 15, description: "Gets buyer to commit — EMD, contract, walkthrough" },
      { name: "Follow-Up Setup", maxPoints: 10, description: "If not closing now, sets clear follow-up timeline" },
    ],
  },
  {
    id: "acq-followup",
    name: "Follow-Up Call",
    role: "acquisitions",
    callType: "follow_up",
    totalPoints: 100,
    criticalFailures: [
      "No reference to why they're calling back",
      "Sounds like they're reading from a generic script",
    ],
    talkRatioTarget: { min: 30, max: 45 },
    criteria: [
      { name: "Context & Personalization", maxPoints: 20, description: "References prior conversations, shows they remember the seller" },
      { name: "Updated Qualification", maxPoints: 20, description: "Checks for changes in timeline, motivation, or competing offers" },
      { name: "Value Reinforcement", maxPoints: 15, description: "Reminds seller of benefits (speed, no repairs, certainty)" },
      { name: "Objection Handling", maxPoints: 20, description: "Addresses lingering concerns or new objections" },
      { name: "Advancement", maxPoints: 15, description: "Moves deal forward — sets appointment, presents offer, or gets a yes" },
      { name: "Professionalism", maxPoints: 10, description: "Maintains professional, respectful tone throughout" },
    ],
  },
  {
    id: "lead-cold",
    name: "Lead Manager Cold Call",
    role: "lead_manager",
    callType: "cold_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not verify property address",
      "Argues with the seller",
    ],
    talkRatioTarget: { min: 25, max: 40 },
    criteria: [
      { name: "Introduction", maxPoints: 15, description: "Clear, confident intro — name, company, reason for calling" },
      { name: "Quick Qualification", maxPoints: 25, description: "Efficiently determines if there's motivation to sell" },
      { name: "Rapport", maxPoints: 15, description: "Builds enough trust to continue the conversation" },
      { name: "Information Capture", maxPoints: 20, description: "Gets key data: motivation, timeline, condition, price range" },
      { name: "Handoff Setup", maxPoints: 15, description: "Sets up a callback or transfer to acquisitions" },
      { name: "Tone & Energy", maxPoints: 10, description: "Sounds natural, not scripted; matches seller's energy" },
    ],
  },
];

const ALGORITHM_DEFAULTS: AlgorithmConfig = {
  inventorySort: {
    newLeadWeight: 100,
    staleContactWeight: 80,
    highMotivationWeight: 90,
    appointmentTodayWeight: 95,
    offerExpiringWeight: 85,
    contractDeadlineWeight: 70,
  },
  buyerMatch: {
    marketMatchWeight: 40,
    priceRangeWeight: 30,
    propertyTypeWeight: 15,
    speedToCloseWeight: 15,
  },
  taskSort: {
    urgentCallbackWeight: 100,
    missedCallWeight: 90,
    appointmentPrepWeight: 80,
    followUpWeight: 70,
    coldCallWeight: 50,
  },
};

const ROLEPLAY_PERSONAS: RoleplayPersona[] = [
  {
    id: "re-motivated-seller",
    name: "Motivated Mary",
    description: "A distressed seller who inherited a property and needs to sell fast due to tax liens",
    role: "acquisitions",
    difficulty: "beginner",
    personality: "Anxious but cooperative. Willing to sell below market if you can close quickly.",
    scenario: "Inherited property with $12K in back taxes. Lives out of state. Just wants it gone.",
    objections: ["I need to talk to my siblings first", "Can you do a little more?", "How fast can you actually close?"],
  },
  {
    id: "re-skeptical-seller",
    name: "Skeptical Steve",
    description: "A seller who's been burned by wholesalers before and doesn't trust investors",
    role: "acquisitions",
    difficulty: "intermediate",
    personality: "Guarded and confrontational. Tests your knowledge. Had a bad experience with a previous investor who never closed.",
    scenario: "Owner-occupied property, behind on mortgage. Wary of investors. Asking retail price.",
    objections: ["Last guy who said that never closed", "Why should I sell to you for less than market?", "I can just list it with an agent", "Are you even going to buy it or just assign it?"],
  },
  {
    id: "re-analytical-seller",
    name: "Analytical Amy",
    description: "A highly informed seller who knows ARV, comps, and market conditions",
    role: "acquisitions",
    difficulty: "advanced",
    personality: "Calm, numbers-driven, has done homework. Won't accept lowball offers without data.",
    scenario: "Divorce situation, nice property, knows the comps. Wants top dollar but needs speed.",
    objections: ["The Zillow estimate is $X", "I know my property is worth more than that", "Show me the comparable sales", "What's your assignment fee going to be?"],
  },
  {
    id: "re-tire-kicker-seller",
    name: "Tire-Kicker Tom",
    description: "A seller with no real motivation who is just exploring options",
    role: "lead_manager",
    difficulty: "intermediate",
    personality: "Friendly but noncommittal. Says 'maybe' to everything. No urgency.",
    scenario: "Property is paid off, no financial pressure. Just curious what investors would pay.",
    objections: ["I'm not in any rush", "I'm just seeing what my options are", "I might just keep renting it out", "Let me think about it"],
  },
  {
    id: "re-cash-buyer-new",
    name: "New Buyer Nick",
    description: "A new cash buyer looking for their first deal, lots of questions",
    role: "dispositions",
    difficulty: "beginner",
    personality: "Eager but cautious. Asks lots of questions about the process and numbers.",
    scenario: "Has $80K liquid. Wants to flip. Never bought from a wholesaler before.",
    objections: ["How do I know the ARV is accurate?", "What if the repairs cost more?", "Can I see it first?", "What's an assignment fee?"],
  },
  {
    id: "re-cash-buyer-exp",
    name: "Experienced Eddie",
    description: "A seasoned investor who buys 5+ deals per month, very demanding",
    role: "dispositions",
    difficulty: "advanced",
    personality: "Blunt, efficient, numbers-only. Will walk if the deal doesn't pencil. Values your time and his.",
    scenario: "Buys 5-10 properties/month. Has own crew. Only wants deals at 70% ARV minus repairs.",
    objections: ["These numbers don't work at that price", "I need it at 65%", "Your last deal had inflated ARV", "I can get this direct for less"],
  },
];

const TRAINING_CATEGORIES: TrainingCategory[] = [
  { code: "cold-calling", name: "Cold Calling Mastery", description: "Techniques for effective first-contact seller outreach", order: 0 },
  { code: "negotiation", name: "Negotiation Skills", description: "How to negotiate win-win deals with sellers and buyers", order: 1 },
  { code: "objection-handling", name: "Objection Handling", description: "Frameworks for overcoming common seller and buyer objections", order: 2 },
  { code: "rapport-building", name: "Rapport Building", description: "Building trust and connection on calls", order: 3 },
  { code: "deal-analysis", name: "Deal Analysis", description: "Running comps, estimating repairs, calculating MAO", role: "acquisitions", order: 4 },
  { code: "dispo-pitching", name: "Dispo Pitching", description: "How to present deals to cash buyers effectively", role: "dispositions", order: 5 },
  { code: "follow-up", name: "Follow-Up Systems", description: "Consistent follow-up strategies for nurturing leads", order: 6 },
  { code: "closing", name: "Closing Techniques", description: "Getting the contract signed or the assignment accepted", order: 7 },
  { code: "crm-workflow", name: "CRM & Workflow", description: "Using GHL and Gunner effectively for pipeline management", order: 8 },
  { code: "mindset", name: "Mindset & Motivation", description: "Staying sharp, handling rejection, maintaining energy", order: 9 },
];

const GRADING_PHILOSOPHY: GradingPhilosophy = {
  overview: "Grading in RE wholesaling prioritizes rapport and discovery over hard closes. A great call uncovers motivation, builds trust, and advances the deal — even if no offer is made. We grade on process, not outcome.",
  criticalFailurePolicy: "Any critical failure (e.g., making an offer without discovering motivation, being rude) results in an automatic cap of 50% on the call score, regardless of other criteria scores.",
  talkRatioGuidance: "The seller should be talking 55-70% of the time on acquisition calls. If the rep is talking more than 50%, they're pitching, not discovering. Dispo calls can be 45-55% rep talk since you're presenting a deal.",
  roleSpecific: {
    acquisitions: "Focus on depth of motivation discovery, quality of rapport, and whether the rep advanced the deal toward an offer or appointment. Penalize for presenting numbers too early.",
    lead_manager: "Efficiency matters. Can they qualify or disqualify in under 5 minutes? Do they capture key data (name, address, motivation, timeline)? Do they route warm leads correctly?",
    dispositions: "Grade on deal presentation clarity, number accuracy, urgency creation, and buyer commitment. The best dispo reps match deals to the right buyers, not just blast to everyone.",
    tc: "Transaction coordinators are graded on communication clarity, timeline accuracy, and proactive updates. They should never let a deal stall without the team knowing why.",
  },
};

export const RE_WHOLESALING_PLAYBOOK: IndustryPlaybook = {
  code: "re-wholesaling",
  name: "Real Estate Wholesaling",
  terminology: {
    contact: "Seller",
    contactPlural: "Sellers",
    asset: "Property",
    assetPlural: "Properties",
    deal: "Deal",
    dealPlural: "Deals",
    walkthrough: "Walkthrough",
  },
  roles: ROLES,
  stages: STAGES,
  callTypes: CALL_TYPES,
  rubrics: RUBRICS,
  outcomeTypes: [
    "Appointment Set",
    "Offer Made",
    "Offer Accepted",
    "Contract Signed",
    "Follow-Up Scheduled",
    "Not Interested",
    "Wrong Number",
    "Voicemail",
    "DNC Request",
    "Dead Lead",
  ],
  kpiFunnelStages: [
    "Leads Generated",
    "Contacts Made",
    "Appointments Set",
    "Offers Made",
    "Contracts Signed",
    "Deals Closed",
  ],
  algorithmDefaults: ALGORITHM_DEFAULTS,
  roleplayPersonas: ROLEPLAY_PERSONAS,
  trainingCategories: TRAINING_CATEGORIES,
  gradingPhilosophy: GRADING_PHILOSOPHY,
  taskCategories: [
    { code: "new_lead", name: "New Lead" },
    { code: "follow_up", name: "Follow Up" },
    { code: "admin", name: "Admin" },
    { code: "reschedule", name: "Reschedule" },
  ],
  classificationLabels: {
    "Interested": { label: "Interested", color: "green" },
    "Not Interested": { label: "Not Interested", color: "red" },
    "Follow-Up Scheduled": { label: "Follow-Up Scheduled", color: "amber" },
    "Offer Rejected": { label: "Offer Rejected", color: "red" },
    "Offer Accepted": { label: "Offer Accepted", color: "green" },
    "No Answer": { label: "No Answer", color: "gray" },
    "Voicemail": { label: "Voicemail", color: "gray" },
    "Callback Requested": { label: "Callback Requested", color: "amber" },
    "Conversation": { label: "Conversation", color: "green" },
    "Admin Call": { label: "Admin Call", color: "gray" },
  },
};
