import type { IndustryPlaybook, RoleDef, StageDef, CallTypeDef, RubricDef, AlgorithmConfig } from "../../shared/types";

const ROLES: RoleDef[] = [
  { code: "acquisitions", name: "Acquisitions Manager", description: "Negotiates deals with sellers, runs comps, makes offers", color: "#6366f1" },
  { code: "dispositions", name: "Dispositions Manager", description: "Sells contracts to cash buyers, manages buyer list", color: "#8b5cf6" },
  { code: "lead_manager", name: "Lead Manager", description: "First contact with inbound leads, qualifies and routes", color: "#0ea5e9" },
  { code: "tc", name: "Transaction Coordinator", description: "Manages contracts, title, inspections through closing", color: "#10b981" },
];

const STAGES: StageDef[] = [
  { code: "new_lead", name: "New Lead", pipeline: "acquisitions", order: 0 },
  { code: "contacted", name: "Contacted", pipeline: "acquisitions", order: 1 },
  { code: "qualified", name: "Qualified", pipeline: "acquisitions", order: 2 },
  { code: "appointment_set", name: "Appointment Set", pipeline: "acquisitions", order: 3 },
  { code: "offer_made", name: "Offer Made", pipeline: "acquisitions", order: 4 },
  { code: "under_contract", name: "Under Contract", pipeline: "acquisitions", order: 5 },
  { code: "dispo", name: "In Dispo", pipeline: "dispositions", order: 6 },
  { code: "assigned_buyer", name: "Assigned to Buyer", pipeline: "dispositions", order: 7 },
  { code: "closing", name: "Closing", pipeline: "dispositions", order: 8 },
  { code: "closed", name: "Closed", pipeline: "dispositions", order: 9 },
  { code: "dead", name: "Dead", pipeline: "acquisitions", order: 99 },
];

const CALL_TYPES: CallTypeDef[] = [
  { code: "cold_call", name: "Cold Call", description: "First outreach to a new lead from a list" },
  { code: "warm_call", name: "Warm Call", description: "Follow-up with a lead who has shown interest" },
  { code: "inbound", name: "Inbound Call", description: "Seller-initiated call from marketing" },
  { code: "follow_up", name: "Follow Up", description: "Scheduled callback or nurture touch" },
  { code: "offer_call", name: "Offer Call", description: "Presenting or negotiating an offer with the seller" },
  { code: "dispo_call", name: "Dispo Call", description: "Pitching a deal to a cash buyer" },
];

const RUBRICS: RubricDef[] = [
  {
    id: "acq-cold",
    name: "Acquisitions Cold Call",
    role: "acquisitions",
    callType: "cold_call",
    totalPoints: 100,
    criticalFailures: [
      "Caller does not confirm seller's name",
      "Caller makes an offer without asking about motivation",
      "Caller is rude or argumentative",
    ],
    talkRatioTarget: { min: 30, max: 45 },
    criteria: [
      { name: "Introduction & Rapport", maxPoints: 15, description: "Introduces self and company clearly, builds initial rapport" },
      { name: "Reason for Call", maxPoints: 10, description: "States purpose clearly — why calling about their property" },
      { name: "Seller Motivation", maxPoints: 20, description: "Uncovers why the seller wants/needs to sell (timeline, situation)" },
      { name: "Property Condition", maxPoints: 15, description: "Asks about condition, repairs needed, occupancy" },
      { name: "Financial Discovery", maxPoints: 15, description: "Discovers mortgage balance, liens, asking price expectations" },
      { name: "Timeline & Urgency", maxPoints: 10, description: "Establishes seller's timeline and urgency level" },
      { name: "Next Steps & Close", maxPoints: 15, description: "Sets a clear next step — appointment, follow-up, or offer" },
    ],
  },
  {
    id: "acq-warm",
    name: "Acquisitions Warm/Follow-Up",
    role: "acquisitions",
    callType: "warm_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not reference previous conversation or context",
      "Pushes for appointment without re-qualifying",
    ],
    talkRatioTarget: { min: 30, max: 50 },
    criteria: [
      { name: "Context Recall", maxPoints: 15, description: "References previous conversation, builds continuity" },
      { name: "Updated Situation", maxPoints: 20, description: "Checks if anything has changed since last contact" },
      { name: "Deeper Motivation", maxPoints: 20, description: "Digs deeper into seller's pain points and motivation" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles seller objections professionally and persuasively" },
      { name: "Commitment / Next Step", maxPoints: 15, description: "Secures appointment, offer acceptance, or concrete next step" },
      { name: "Tone & Empathy", maxPoints: 10, description: "Maintains professional, empathetic tone throughout" },
    ],
  },
  {
    id: "acq-offer",
    name: "Acquisitions Offer Presentation",
    role: "acquisitions",
    callType: "offer_call",
    totalPoints: 100,
    criticalFailures: [
      "Presents number without justification or context",
      "Gets defensive when seller pushes back on price",
    ],
    talkRatioTarget: { min: 35, max: 50 },
    criteria: [
      { name: "Recap & Frame", maxPoints: 15, description: "Recaps seller situation before presenting number" },
      { name: "Number Presentation", maxPoints: 20, description: "Presents offer confidently with clear justification" },
      { name: "Value Anchoring", maxPoints: 15, description: "Anchors value on convenience, speed, certainty — not just price" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles price pushback calmly and with logic" },
      { name: "Urgency Creation", maxPoints: 15, description: "Creates appropriate urgency without pressure tactics" },
      { name: "Contract / Close", maxPoints: 15, description: "Moves toward contract signing or clear counter path" },
    ],
  },
  {
    id: "acq-inbound",
    name: "Inbound Seller Call",
    role: "lead_manager",
    callType: "inbound",
    totalPoints: 100,
    criticalFailures: [
      "Does not capture seller's name and property address",
      "Lets caller hang up without setting a next step",
    ],
    talkRatioTarget: { min: 25, max: 40 },
    criteria: [
      { name: "Speed & Energy", maxPoints: 15, description: "Answers promptly with enthusiasm and professionalism" },
      { name: "Information Capture", maxPoints: 20, description: "Captures name, address, phone, email within first 2 min" },
      { name: "Qualification", maxPoints: 20, description: "Asks motivation, timeline, condition, price expectations" },
      { name: "Rapport Building", maxPoints: 15, description: "Builds trust and makes seller feel comfortable" },
      { name: "Appointment Setting", maxPoints: 20, description: "Converts call to a scheduled appointment or callback" },
      { name: "CRM Entry", maxPoints: 10, description: "Confirms info will be captured and follow-up scheduled" },
    ],
  },
  {
    id: "dispo-buyer",
    name: "Dispositions Buyer Call",
    role: "dispositions",
    callType: "dispo_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not confirm buyer's buying criteria before pitching",
      "Cannot answer basic questions about the property",
    ],
    talkRatioTarget: { min: 40, max: 55 },
    criteria: [
      { name: "Buyer Criteria Confirm", maxPoints: 15, description: "Confirms buyer's target area, price range, and property type" },
      { name: "Deal Presentation", maxPoints: 25, description: "Presents deal clearly — address, ARV, rehab estimate, assignment fee" },
      { name: "Urgency & Scarcity", maxPoints: 15, description: "Communicates deal timeline and competitive interest" },
      { name: "Objection Handling", maxPoints: 20, description: "Handles buyer concerns about numbers, area, condition" },
      { name: "Closing for Commitment", maxPoints: 15, description: "Gets buyer to commit — EMD, contract, walkthrough" },
      { name: "Follow-Up Setup", maxPoints: 10, description: "If not closing now, sets clear follow-up timeline" },
    ],
  },
  {
    id: "acq-followup",
    name: "Follow-Up Call",
    role: "acquisitions",
    callType: "follow_up",
    totalPoints: 100,
    criticalFailures: [
      "No reference to why they're calling back",
      "Sounds like they're reading from a generic script",
    ],
    talkRatioTarget: { min: 30, max: 45 },
    criteria: [
      { name: "Context & Personalization", maxPoints: 20, description: "References prior conversations, shows they remember the seller" },
      { name: "Updated Qualification", maxPoints: 20, description: "Checks for changes in timeline, motivation, or competing offers" },
      { name: "Value Reinforcement", maxPoints: 15, description: "Reminds seller of benefits (speed, no repairs, certainty)" },
      { name: "Objection Handling", maxPoints: 20, description: "Addresses lingering concerns or new objections" },
      { name: "Advancement", maxPoints: 15, description: "Moves deal forward — sets appointment, presents offer, or gets a yes" },
      { name: "Professionalism", maxPoints: 10, description: "Maintains professional, respectful tone throughout" },
    ],
  },
  {
    id: "lead-cold",
    name: "Lead Manager Cold Call",
    role: "lead_manager",
    callType: "cold_call",
    totalPoints: 100,
    criticalFailures: [
      "Does not verify property address",
      "Argues with the seller",
    ],
    talkRatioTarget: { min: 25, max: 40 },
    criteria: [
      { name: "Introduction", maxPoints: 15, description: "Clear, confident intro — name, company, reason for calling" },
      { name: "Quick Qualification", maxPoints: 25, description: "Efficiently determines if there's motivation to sell" },
      { name: "Rapport", maxPoints: 15, description: "Builds enough trust to continue the conversation" },
      { name: "Information Capture", maxPoints: 20, description: "Gets key data: motivation, timeline, condition, price range" },
      { name: "Handoff Setup", maxPoints: 15, description: "Sets up a callback or transfer to acquisitions" },
      { name: "Tone & Energy", maxPoints: 10, description: "Sounds natural, not scripted; matches seller's energy" },
    ],
  },
];

const ALGORITHM_DEFAULTS: AlgorithmConfig = {
  inventorySort: {
    newLeadWeight: 100,
    staleContactWeight: 80,
    highMotivationWeight: 90,
    appointmentTodayWeight: 95,
    offerExpiringWeight: 85,
    contractDeadlineWeight: 70,
  },
  buyerMatch: {
    marketMatchWeight: 40,
    priceRangeWeight: 30,
    propertyTypeWeight: 15,
    speedToCloseWeight: 15,
  },
  taskSort: {
    urgentCallbackWeight: 100,
    missedCallWeight: 90,
    appointmentPrepWeight: 80,
    followUpWeight: 70,
    coldCallWeight: 50,
  },
};

export const RE_WHOLESALING_PLAYBOOK: IndustryPlaybook = {
  code: "re-wholesaling",
  name: "Real Estate Wholesaling",
  terminology: {
    contact: "Seller",
    contactPlural: "Sellers",
    asset: "Property",
    assetPlural: "Properties",
    deal: "Deal",
    dealPlural: "Deals",
    walkthrough: "Walkthrough",
  },
  roles: ROLES,
  stages: STAGES,
  callTypes: CALL_TYPES,
  rubrics: RUBRICS,
  outcomeTypes: [
    "Appointment Set",
    "Offer Made",
    "Offer Accepted",
    "Contract Signed",
    "Follow-Up Scheduled",
    "Not Interested",
    "Wrong Number",
    "Voicemail",
    "DNC Request",
    "Dead Lead",
  ],
  kpiFunnelStages: [
    "Leads Generated",
    "Contacts Made",
    "Appointments Set",
    "Offers Made",
    "Contracts Signed",
    "Deals Closed",
  ],
  algorithmDefaults: ALGORITHM_DEFAULTS,
};
