-- LM-DEAC pre-soak baseline persistence.
-- Phase 0d of the LLM Rewiring Plan (docs/LLM_REWIRING_PLAN.md).
-- Pre-soak comparator for the +25% LM-DEAC soak target.
-- Generated by lib/kpis/lm-deac.ts.

CREATE TABLE "lm_deac_baselines" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "dials" INTEGER NOT NULL,
    "tasks_completed" INTEGER NOT NULL,
    "appts_set" INTEGER NOT NULL,
    "script_adherence_score" DOUBLE PRECISION NOT NULL,
    "composite" DOUBLE PRECISION NOT NULL,
    "captured_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" JSONB,

    CONSTRAINT "lm_deac_baselines_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "lm_deac_baselines_tenant_id_user_id_date_key"
    ON "lm_deac_baselines"("tenant_id", "user_id", "date");

CREATE INDEX "lm_deac_baselines_tenant_id_date_idx"
    ON "lm_deac_baselines"("tenant_id", "date");
